name: Tag new releases of cfn-lint

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"

jobs:
  tag-new-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ADRIANMACE_PAT }}

      - name: Get the current tag from the file
        run: |
          echo "VERSION=$(sed -r -e 's/^.*==(.*)$/\1/g' requirements.txt)" >> $GITHUB_ENV

      - name: Tag commit with cfn-lint version
        run: |
          git tag --force 'v${{ env.VERSION }}' master

      - name: Push commits to Github
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ADRIANMACE_PAT }}
          tags: true
          force: true
