name: Push Docker Image

on:
  push:
    branches:
    - master
    paths-ignore:
    - '**.md'

jobs:
  push:
    runs-on: ubuntu-18.04
    steps:


    - name: Set env
      run: |
        curl -V
        jq -V
        LATEST_TAG=$(curl -s https://api.github.com/repos/aws-cloudformation/cfn-python-lint/releases | jq -r '.[0].tag_name')
        echo $LATEST_TAG
        echo "::set-env name=LATEST_TAG::${LATEST_TAG}"

    - name: checkout aws-cloudformation/cfn-python-lint:${{ env.LATEST_TAG }}
      uses: actions/checkout@v2
      with:
        repository: aws-cloudformation/cfn-python-lint
        fetch-depth: 0
        ref: ${{ env.LATEST_TAG }}
        path: cfn-lint

    - name: ls
      run: |
        ls -la
        ls -la cfn-lint

